// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RegistoCriminal.Data;

#nullable disable

namespace RegistoCriminal.Migrations
{
    [DbContext(typeof(RegistoCriminalContext))]
    [Migration("20250522094536_MigrtionsOfNameandEstado")]
    partial class MigrtionsOfNameandEstado
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AspNetRoleAspNetUser", b =>
                {
                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("RoleId", "UserId");

                    b.ToTable("AspNetRoleAspNetUser");
                });

            modelBuilder.Entity("AspNetUserRole", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex(new[] { "RoleId" }, "IX_AspNetUserRoles_RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("RegistoCriminal.Entities.AspNetRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "NormalizedName" }, "RoleNameIndex")
                        .IsUnique()
                        .HasFilter("([NormalizedName] IS NOT NULL)");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("RegistoCriminal.Entities.AspNetRoleClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "RoleId" }, "IX_AspNetRoleClaims_RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("RegistoCriminal.Entities.AspNetUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "NormalizedEmail" }, "EmailIndex");

                    b.HasIndex(new[] { "NormalizedUserName" }, "UserNameIndex")
                        .IsUnique()
                        .HasFilter("([NormalizedUserName] IS NOT NULL)");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("RegistoCriminal.Entities.AspNetUserClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "UserId" }, "IX_AspNetUserClaims_UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("RegistoCriminal.Entities.AspNetUserLogin", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex(new[] { "UserId" }, "IX_AspNetUserLogins_UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("RegistoCriminal.Entities.AspNetUserToken", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("RegistoCriminal.Entities.CertificadoRegisto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Conteudo")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("conteudo");

                    b.Property<DateTime?>("DataEmissao")
                        .HasColumnType("datetime")
                        .HasColumnName("dataEmissao");

                    b.Property<DateTime?>("DataValidade")
                        .HasColumnType("datetime")
                        .HasColumnName("dataValidade");

                    b.Property<string>("EstadoCertificado")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("estadoCertificado");

                    b.Property<int>("IdFuncionarioEmissor")
                        .HasColumnType("int")
                        .HasColumnName("idFuncionarioEmissor");

                    b.Property<int>("IdSolicitacao")
                        .HasColumnType("int")
                        .HasColumnName("idSolicitacao");

                    b.Property<string>("NumeroReferencia")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("numeroReferencia");

                    b.HasKey("Id")
                        .HasName("PK__Certific__3213E83F5E822AA9");

                    b.HasIndex("IdFuncionarioEmissor");

                    b.HasIndex("IdSolicitacao");

                    b.ToTable("CertificadoRegisto");
                });

            modelBuilder.Entity("RegistoCriminal.Entities.Cidadao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Datanascimento")
                        .HasColumnType("date")
                        .HasColumnName("datanascimento");

                    b.Property<string>("Distrito")
                        .HasMaxLength(60)
                        .IsUnicode(false)
                        .HasColumnType("varchar(60)")
                        .HasColumnName("distrito");

                    b.Property<string>("Endereco")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("endereco");

                    b.Property<string>("IdUtilizador")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("idUtilizador");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("nomecompleto");

                    b.Property<string>("NumBi")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("numBi");

                    b.Property<string>("Provincia")
                        .HasMaxLength(60)
                        .IsUnicode(false)
                        .HasColumnType("varchar(60)")
                        .HasColumnName("provincia");

                    b.HasKey("Id")
                        .HasName("PK__Cidadao__3213E83F7C3C30EE");

                    b.HasIndex("IdUtilizador");

                    b.ToTable("Cidadao");
                });

            modelBuilder.Entity("RegistoCriminal.Entities.FuncionarioJudicial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cargo")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("cargo");

                    b.Property<string>("Departamento")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("departamento");

                    b.Property<string>("IdUtilizador")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("idUtilizador");

                    b.Property<string>("Nivelacesso")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("nivelacesso");

                    b.HasKey("Id")
                        .HasName("PK__Funciona__3213E83FECB2DE74");

                    b.HasIndex("IdUtilizador");

                    b.ToTable("FuncionarioJudicial");
                });

            modelBuilder.Entity("RegistoCriminal.Entities.Log", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Acao")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("ACAO");

                    b.Property<string>("Detalhes")
                        .HasMaxLength(600)
                        .IsUnicode(false)
                        .HasColumnType("varchar(600)")
                        .HasColumnName("DETALHES");

                    b.Property<string>("Iduser")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("IDUSER");

                    b.Property<string>("Ipaddress")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("ipaddress");

                    b.HasKey("Id")
                        .HasName("PK__logs__3214EC272ABE76E2");

                    b.HasIndex("Iduser");

                    b.ToTable("logs");
                });

            modelBuilder.Entity("RegistoCriminal.Entities.Pagamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Datapagamento")
                        .HasColumnType("datetime")
                        .HasColumnName("datapagamento");

                    b.Property<string>("Estado")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("estado");

                    b.Property<int>("IdSolicitacao")
                        .HasColumnType("int")
                        .HasColumnName("idSolicitacao");

                    b.Property<string>("Metodo")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("metodo");

                    b.Property<string>("Referencia")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("referencia");

                    b.Property<decimal?>("Valor")
                        .HasColumnType("decimal(17, 2)")
                        .HasColumnName("valor");

                    b.HasKey("Id")
                        .HasName("PK__pagament__3213E83F32BFC9AE");

                    b.HasIndex("IdSolicitacao");

                    b.ToTable("pagamento");
                });

            modelBuilder.Entity("RegistoCriminal.Entities.RegistosCriminal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Cumprido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("cumprido");

                    b.Property<DateOnly?>("DataOcorrencia")
                        .HasColumnType("date")
                        .HasColumnName("dataOcorrencia");

                    b.Property<DateTime?>("DataSentenca")
                        .HasColumnType("datetime")
                        .HasColumnName("dataSentenca");

                    b.Property<int>("IdCidado")
                        .HasColumnType("int")
                        .HasColumnName("idCidado");

                    b.Property<string>("NumeroProcesso")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("numeroProcesso");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("observacoes");

                    b.Property<string>("Sentenca")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("sentenca");

                    b.Property<string>("TipoOcorrencia")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("tipoOcorrencia");

                    b.HasKey("Id")
                        .HasName("PK__Registos__3213E83FA0006D4C");

                    b.HasIndex("IdCidado");

                    b.ToTable("RegistosCriminal");
                });

            modelBuilder.Entity("RegistoCriminal.Entities.Solicitacaoregisto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Datasolicitacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("datasolicitacao")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("estado");

                    b.Property<string>("Finalidade")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("finalidade");

                    b.Property<string>("Formapagamento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("formapagamento");

                    b.Property<int>("IdCidado")
                        .HasColumnType("int")
                        .HasColumnName("idCidado");

                    b.Property<bool?>("Pago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("pago");

                    b.Property<bool?>("Urgencia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("urgencia");

                    b.HasKey("Id")
                        .HasName("PK__Solicita__3213E83F4B4E5BC2");

                    b.HasIndex("IdCidado");

                    b.ToTable("Solicitacaoregisto");
                });

            modelBuilder.Entity("AspNetUserRole", b =>
                {
                    b.HasOne("RegistoCriminal.Entities.AspNetRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RegistoCriminal.Entities.AspNetUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RegistoCriminal.Entities.AspNetRoleClaim", b =>
                {
                    b.HasOne("RegistoCriminal.Entities.AspNetRole", "Role")
                        .WithMany("AspNetRoleClaims")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("RegistoCriminal.Entities.AspNetUserClaim", b =>
                {
                    b.HasOne("RegistoCriminal.Entities.AspNetUser", "User")
                        .WithMany("AspNetUserClaims")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("RegistoCriminal.Entities.AspNetUserLogin", b =>
                {
                    b.HasOne("RegistoCriminal.Entities.AspNetUser", "User")
                        .WithMany("AspNetUserLogins")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("RegistoCriminal.Entities.AspNetUserToken", b =>
                {
                    b.HasOne("RegistoCriminal.Entities.AspNetUser", "User")
                        .WithMany("AspNetUserTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("RegistoCriminal.Entities.CertificadoRegisto", b =>
                {
                    b.HasOne("RegistoCriminal.Entities.FuncionarioJudicial", "IdFuncionarioEmissorNavigation")
                        .WithMany("CertificadoRegistos")
                        .HasForeignKey("IdFuncionarioEmissor")
                        .IsRequired()
                        .HasConstraintName("FK__Certifica__idFun__236943A5");

                    b.HasOne("RegistoCriminal.Entities.Solicitacaoregisto", "IdSolicitacaoNavigation")
                        .WithMany("CertificadoRegistos")
                        .HasForeignKey("IdSolicitacao")
                        .IsRequired()
                        .HasConstraintName("FK__Certifica__idSol__245D67DE");

                    b.Navigation("IdFuncionarioEmissorNavigation");

                    b.Navigation("IdSolicitacaoNavigation");
                });

            modelBuilder.Entity("RegistoCriminal.Entities.Cidadao", b =>
                {
                    b.HasOne("RegistoCriminal.Entities.AspNetUser", "IdUtilizadorNavigation")
                        .WithMany("Cidadaos")
                        .HasForeignKey("IdUtilizador")
                        .HasConstraintName("FK__Cidadao__idUtili__17036CC0");

                    b.Navigation("IdUtilizadorNavigation");
                });

            modelBuilder.Entity("RegistoCriminal.Entities.FuncionarioJudicial", b =>
                {
                    b.HasOne("RegistoCriminal.Entities.AspNetUser", "IdUtilizadorNavigation")
                        .WithMany("FuncionarioJudicials")
                        .HasForeignKey("IdUtilizador")
                        .IsRequired()
                        .HasConstraintName("FK__Funcionar__idUti__14270015");

                    b.Navigation("IdUtilizadorNavigation");
                });

            modelBuilder.Entity("RegistoCriminal.Entities.Log", b =>
                {
                    b.HasOne("RegistoCriminal.Entities.AspNetUser", "IduserNavigation")
                        .WithMany("Logs")
                        .HasForeignKey("Iduser")
                        .IsRequired()
                        .HasConstraintName("FK__logs__IDUSER__114A936A");

                    b.Navigation("IduserNavigation");
                });

            modelBuilder.Entity("RegistoCriminal.Entities.Pagamento", b =>
                {
                    b.HasOne("RegistoCriminal.Entities.Solicitacaoregisto", "IdSolicitacaoNavigation")
                        .WithMany("Pagamentos")
                        .HasForeignKey("IdSolicitacao")
                        .IsRequired()
                        .HasConstraintName("FK__pagamento__idSol__2739D489");

                    b.Navigation("IdSolicitacaoNavigation");
                });

            modelBuilder.Entity("RegistoCriminal.Entities.RegistosCriminal", b =>
                {
                    b.HasOne("RegistoCriminal.Entities.Cidadao", "IdCidadoNavigation")
                        .WithMany("RegistosCriminals")
                        .HasForeignKey("IdCidado")
                        .IsRequired()
                        .HasConstraintName("FK__RegistosC__idCid__1AD3FDA4");

                    b.Navigation("IdCidadoNavigation");
                });

            modelBuilder.Entity("RegistoCriminal.Entities.Solicitacaoregisto", b =>
                {
                    b.HasOne("RegistoCriminal.Entities.Cidadao", "IdCidadoNavigation")
                        .WithMany("Solicitacaoregistos")
                        .HasForeignKey("IdCidado")
                        .IsRequired()
                        .HasConstraintName("FK__Solicitac__idCid__208CD6FA");

                    b.Navigation("IdCidadoNavigation");
                });

            modelBuilder.Entity("RegistoCriminal.Entities.AspNetRole", b =>
                {
                    b.Navigation("AspNetRoleClaims");
                });

            modelBuilder.Entity("RegistoCriminal.Entities.AspNetUser", b =>
                {
                    b.Navigation("AspNetUserClaims");

                    b.Navigation("AspNetUserLogins");

                    b.Navigation("AspNetUserTokens");

                    b.Navigation("Cidadaos");

                    b.Navigation("FuncionarioJudicials");

                    b.Navigation("Logs");
                });

            modelBuilder.Entity("RegistoCriminal.Entities.Cidadao", b =>
                {
                    b.Navigation("RegistosCriminals");

                    b.Navigation("Solicitacaoregistos");
                });

            modelBuilder.Entity("RegistoCriminal.Entities.FuncionarioJudicial", b =>
                {
                    b.Navigation("CertificadoRegistos");
                });

            modelBuilder.Entity("RegistoCriminal.Entities.Solicitacaoregisto", b =>
                {
                    b.Navigation("CertificadoRegistos");

                    b.Navigation("Pagamentos");
                });
#pragma warning restore 612, 618
        }
    }
}
